### ISSUE TITLE
Bump six 1.5.2 to 1.10.0

### ISSUE THREAD

**Issue by copperwall** [spacedogXYZ/call-power#18]
I tried building a Docker image on the master branch and got the following error.

```
Installing collected packages: pytz, Babel, Werkzeug, MarkupSafe, Jinja2, itsdangerous, Flask, webassets, Flask-Assets, speaklater, Flask-Babel, Flask-Cache, Flask-Jsonpify, Flask-Login, blinker, Flask-Mail, SQLAlchemy, six, python-dateutil, python-mimeparse, mimerender, Flask-Restless, Flask-SQLAlchemy, Flask-Script, shortuuid, flask-store, WTForms, Flask-WTF, Mako, PyYAML, SQLAlchemy-Utils, decorator, validators, infinity, intervals, WTForms-Components, alembic, httplib2, phonenumbers, requests, pygeocodio, pystache, args, clint, sunlight, twilio, unittest2, boto, greenlet, gevent, psycopg2, gevent-psycopg2, redis, uWSGI, Flask-DebugToolbar, Flask-Testing, nose, cssmin
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Running setup.py develop for flask-store
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/opt/src/flask-store/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    /opt/src/flask-store/setup.py:64: UserWarning: REQS.TESTING.txt was not found
      warnings.warn('{0} was not found'.format(filename))
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/src/flask-store/setup.py", line 142, in <module>
        keywords=['Flask', 'Files', 'Storage'])
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 320, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 386, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2306, in require
        items = working_set.resolve(reqs, env, installer)
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 853, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (six 1.5.2 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('six>=1.10.0'))
```

It looks like `flask-store` requires a more recent version of `six`.

**Comment by jlev** [comment]
@copperwall thanks for the bug report. I don't use Docker images directly, so didn't notice the failed builds.

Let me know if you have other questions. There are a lot of pending feature requests from other users, and I'd love to know how else you think the system could be improved.

**Comment by copperwall** [comment]
Thanks for the quick fix. I'll let you know if I think of anything useful.
